In [24]:
import numpy as np
import os
import pandas as pd
import matplotlib.pl
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [25]:
df = pd.read_csv("data_classified.csv")

In [26]:
df.head()

Unnamed: 0       WTT       PTI       EQW       SBI       LQE       QWG  \
0           0  0.913917  1.162073  0.567946  0.755464  0.780862  0.352608   
1           1  0.635632  1.003722  0.535342  0.825645  0.924109  0.648450   
2           2  0.721360  1.201493  0.921990  0.855595  1.526629  0.720781   
3           3  1.234204  1.386726  0.653046  0.825624  1.142504  0.875128   
4           4  1.279491  0.949750  0.627280  0.668976  1.232537  0.703727   

        FDJ       PJF       HQE       NXJ  TARGET CLASS  
0  0.759697  0.643798  0.879422  1.231409             1  
1  0.675334  1.013546  0.621552  1.492702             0  
2  1.626351  1.154483  0.957877  1.285597             0  
3  1.409708  1.380003  1.522692  1.153093             1  
4  1.115596  0.646691  1.463812  1.419167             1

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Unnamed: 0    1000 non-null   int64  
 1   WTT           1000 non-null   float64
 2   PTI           1000 non-null   float64
 3   EQW           1000 non-null   float64
 4   SBI           1000 non-null   float64
 5   LQE           1000 non-null   float64
 6   QWG           1000 non-null   float64
 7   FDJ           1000 non-null   float64
 8   PJF           1000 non-null   float64
 9   HQE           1000 non-null   float64
 10  NXJ           1000 non-null   float64
 11  TARGET CLASS  1000 non-null   int64  
dtypes: float64(10), int64(2)
memory usage: 93.9 KB


In [28]:
df = df.drop("Unnamed: 0", axis = 1)

In [29]:
scaler = StandardScaler() 
scaler.fit(df)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [30]:
scaler_features = scaler.transform(df)

In [31]:
scaler_features

array([[-0.12354188,  0.18590747, -0.91343069, ..., -0.9497194 ,
        -0.64331425,  1.        ],
       [-1.08483602, -0.43034845, -1.02531333, ..., -1.82805088,
         0.63675862, -1.        ],
       [-0.78870217,  0.33931821,  0.30151137, ..., -0.68249379,
        -0.37784986, -1.        ],
       ...,
       [ 0.64177714, -0.51308341, -0.17920486, ..., -0.81426092,
         0.11159651,  1.        ],
       [ 0.46707241, -0.98278576, -1.46519359, ...,  0.40602453,
        -0.85567   ,  1.        ],
       [-0.38765353, -0.59589427, -1.4313981 , ...,  0.3369971 ,
         0.01034996,  1.        ]])

In [32]:
df_scft = pd.DataFrame(scaler_features, columns = df.columns)

In [33]:
df_scft.head()

WTT       PTI       EQW       SBI       LQE       QWG       FDJ  \
0 -0.123542  0.185907 -0.913431  0.319629 -1.033637 -2.308375 -0.798951   
1 -1.084836 -0.430348 -1.025313  0.625388 -0.444847 -1.152706 -1.129797   
2 -0.788702  0.339318  0.301511  0.755873  2.031693 -0.870156  2.599818   
3  0.982841  1.060193 -0.621399  0.625299  0.452820 -0.267220  1.750208   
4  1.139275 -0.640392 -0.709819 -0.057175  0.822886 -0.936773  0.596782   

        PJF       HQE       NXJ  TARGET CLASS  
0 -1.482368 -0.949719 -0.643314           1.0  
1 -0.202240 -1.828051  0.636759          -1.0  
2  0.285707 -0.682494 -0.377850          -1.0  
3  1.066491  1.241325 -1.026987           1.0  
4 -1.472352  1.040772  0.276510           1.0

In [35]:
X = df_scft  #feature
y = df['TARGET CLASS']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)


In [43]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1) 

from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       142
           1       1.00      1.00      1.00       158

    accuracy                           1.00       300
   macro avg       1.00      1.00      1.00       300
weighted avg       1.00      1.00      1.00       300

[[142   0]
 [  0 158]]


In [44]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [45]:
y_pred = knn.predict(X_test)

In [46]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       142
           1       1.00      1.00      1.00       158

    accuracy                           1.00       300
   macro avg       1.00      1.00      1.00       300
weighted avg       1.00      1.00      1.00       300

[[142   0]
 [  0 158]]


In [47]:
error_rate = []

for i in range(1,20):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, y_train)
    y_pred_i = knn.predict(X_test)
    error_rate.append(np.mean(y_pred_i != y_test))

In [48]:
plt.figure(figsize=(10,5))
plt.plot(range(1,20),error_rate,color='blue',ls='--',marker='o',markerfacecolor='red', markersize=10)
plt.title('Error Rate vs K Value')
plt.xlabel('K')
plt.ylabel('Error Rate')

NameError: name 'plt' is not defined